### ISSUE TITLE
Sensor to detect if someone is using hotwater

### ISSUE THREAD

**Issue by bruin14** [bosch-thermostat/home-assistant-bosch-custom-component#184]
Hi,
Is there a way to detect the system is currently delivering hotwater? I have a CT200 that shows a (watertap) icon when someone is using hotwater when showering but i don't see a sensor showing a state.

It would be useful to control a bathroom fan based on the state of this sensor.

Thks
Arnold

**Comment by pszafer** [comment]
Make one scan when nobody is using water and second one when tap is visible.

**Comment by bruin14** [comment]
Both scans
[scans.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9180387/scans.zip)
s

**Comment by pszafer** [comment]
So only way to retrieve those data is to fetch this:
```json
{
            "id": "/gateway/ui/icons",
            "type": "stringArray",
            "writeable": 0,
            "recordable": 0,
            "value": [
                "",
                "",
                "",
                ""
            ]
        },
```

It's hard to say how it is working... I don't have enough data.
I have one scan with data:
```json
{
            "id": "/gateway/ui/icons",
            "type": "stringArray",
            "writeable": 0,
            "recordable": 0,
            "value": [
                "",
                "ch on",
                "",
                ""
            ]
        },
```

and yours with:
```json
{
      "id": "/gateway/ui/icons",
      "type": "stringArray",
      "writeable": 0,
      "recordable": 0,
      "value": [
        "",
        "dhw on",
        "",
        ""
      ]
    },

```

My idea right now is to just give you value as sensor with text and maybe during season you'd know what could show as first element of the array, third, fourth etc.

**Comment by bruin14** [comment]
Thks

I made some other scans and checked the easycontrol manual. If you look at
the attachment, i think the 4 icon positions in de manual are the 4
possible icons in the display (4 and 5 in the image). The first one looks
like the away indicator

*Easycontrol in awaymode*
      "id": "/gateway/ui/icons",
      "type": "stringArray",
      "writeable": 0,
      "recordable": 0,
      "value": [
        "away",
        "",
        "",
        ""

The second icon is dhw on, ch on, calendar (and maybe others)

*Easycontrol in awaymode activated by an event*
      "id": "/gateway/ui/icons",
      "type": "stringArray",
      "writeable": 0,
      "recordable": 0,
      "value": [
        "away",
        "calendar",
        "",
        ""
      ]

The last 2 icons are probably error icons. Difficult to check i guess


Op do 28 jul. 2022 om 08:32 schreef Pawel ***@***.***>:

**Comment by pszafer** [comment]
So it can't be CH ON and DHW ON in the same time?

**Comment by bruin14** [comment]
I don't think so
A heater will always give priority to hot water. As far as i know a combi heater cannot do both at the same time.

**Comment by vdg1** [comment]
Hi,

I had a similar "challenge" because I wanted to record the heaters energy consumption for hot water preparation and house heating individually. I used a statistical entity to detect changes in hot water temperature to decide if hot water is currently being consumed (shower, etc) or prepared by the heat pump. A binary sensor goes on when the change of water temperature is positive for a certain time:

```
template:
  - binary_sensor:
      - name: "Preparing hot water"
        state: >
          {{ states('sensor.hot_water_change')|float > 0.002 }}
```

and


```
  - platform: statistics
    name: "Hot water change"
    unique_id: "Hot water change"
    entity_id: sensor.dhw1_actual_temperature
    state_characteristic: change_second
    max_age:
      minutes: 10
    sampling_size: 3
    precision: 3
```
    
This works quite ok for me.
