### ISSUE TITLE
Water Heater: Set operation mode performance

### ISSUE THREAD

**Issue by Bigglesuk** [bosch-thermostat/home-assistant-bosch-custom-component#202]
I'm trying to change the operation mode on my hot water using the bosch integration. I'm using the v0.18.3 version from HACS

my entity is: water_heater.dhw1

If i call a service via Home Assistant dev tools like below:
```
service: water_heater.set_operation_mode
data:
  operation_mode: high_demand
target:
  entity_id: water_heater.dhw1
```

I have no issues getting it to change between High Demand (On) and off.  However, If I try and do exactly the same with a performance which is one of the modes on the operations list - and one I can set in the Bosche app it doesn't do anything. the spelling is lowercase performance as if I use uppercase Performance it gives an error so I know the actual enumeration is correct.

Just to show it switching between the other operation modes with no issues:

![image](https://user-images.githubusercontent.com/22842208/192619583-0c932c1f-6d58-4814-b397-35c351699ddc.png)

Is there something I may be missing?

**Comment by pszafer** [comment]
Enable debug logs to check what's wrong

**Comment by Bigglesuk** [comment]
> Enable debug logs to check what's wrong

I've run the Bosch thermostat: debug_scan service and now have the bosch_scan.json file, or is this additional logs i need to enable?

**Comment by Bigglesuk** [comment]
Ah just found the bit on the page saying i need to put this in config:

```
logger:
  default: warning
  logs:
    custom_components.bosch: debug
    bosch_thermostat_client: debug
```

i will do so
