### ISSUE TITLE
Got 'energyConsumption' value is not allowed

### ISSUE THREAD

**Issue by dagobert** [bosch-thermostat/home-assistant-bosch-custom-component#26]
I have configured using YAML

```
bosch:
  - address: myIP
    password: "mypassword"
    access_token: "mytoken"
    sensors:
      - outdoor_t1
      - hotWater_t2
      - supply_t1
      - supply_t1_setpoint
      - return
      - healthStatus
      - actualPower
      - actualModulation
      - CHpumpModulation
      - energyConsumption
      - systemPressure
```

When starting HASS I get the following errors:

```
2020-03-31 23:52:30 ERROR (MainThread) [homeassistant.components.hassio] Invalid config for [bosch]: value is not allowed @ data['bosch'][0]['sensors'][0]. Got 'energyConsumption'
value is not allowed @ data['bosch'][0]['sensors'][1]. Got 'systemPressure'. (See /config/configuration.yaml, line 183).

```

What is wrong?
