### ISSUE TITLE
Buderus TC100.2 - "Your device is unknown null"

### ISSUE THREAD

**Issue by Bumblebeee19** [bosch-thermostat/home-assistant-bosch-custom-component#87]
Hi everyone,

For the past few weeks, I have been having problems with my Buderus CT100.2 thermostat. I have reset this several times and at first the connections were random even on MyMode. Everything seems to be working again now but it is no longer recognized on HA.
The system tells me *"Your device is unknown null"*, but the model is well recognized.

Custom-component is in v. 0.14.0a and fw Buderus 03.06.03.

I tried to generate a debug_scan but it doesn't work. I can't find the service in the development tools, if I understood the documentation correctly, I have to modify configuration.yaml like this, right?

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    custom_components.bosch: debug
    bosch_thermostat_client: debug
```
I'm new to YAML, HA, HACS and all that, thanks for your understanding :)

Thank you for the follow-up and the excellent work done!
